language: node_js
node_js:
  - 4.0.0

install:
  - rvm install 2.3.1
  - bundle install

cache:
  bundler: true

script:
  - git clone https://github.com/bridgefoundry/code-of-conduct.git
  - (cd code-of-conduct-src; bundle exec jekyll build --destination ../code-of-conduct)
  - rm -rf code-of-conduct-src
  - bundle exec jekyll build

deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  project: bridgefoundry-site

